project:
  type: website
  output-dir: docs
website:
  title: "उपक्रमणिका"
  navbar:
    right:
      - icon: person-badge-fill
        href: https://iambharathgs.in/
      - icon: github
        href: https://github.com/bharathgs
      - icon: twitter
        href: https://twitter.com/iambharathgs
      - icon: linkedin
        href: https://www.linkedin.com/in/iambharathgs/
    background: rgb(242, 239, 231)

format:
  html:
    theme: litera
    css: styles.css



